name: run unit testing

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on:  windows-latest
    steps:
      - name: Checkout Repository and Sub-Modules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
         platform: x64
        
      - name: configure cmake
        run: |
          mkdir build
          cmake -S . -B build -G "MinGW Makefiles"

      - name: Build Unit Tests
        run: |
          cmake --build build --config "Release"

      - name: Execute Unit Tests
        run: |
          ctest --test-dir build -C "Release" -V
