name: Check Pull Request

on:
  # Triggers the workflow on pull request events
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on:  windows-latest
    steps:
      - name: Checkout Repository and Sub-Modules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
         platform: x64
        
      - name: configure cmake
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release
          ctest -C "Release"

      # - name: Build Unit Tests
      #   run: |
      #     cmake --build . --config Release

      - name: Execute Unit Tests
        run: |
          ctest -C "Release"
